name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script:echo "SSH connection successful! Server IP: $(hostname -I)"