name: deploy on push (production)
on:
  push:
    branches:
      - prod  
  workflow_dispatch:
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4

      - name: set ubuntu user own /var/www/html
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: sudo chown -R ubuntu /var/www/html

      - name: copy file to prod server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER_NAME }}
          port: ${{ secrets.PROD_SSH_PORT }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1

      - name: set root user own back
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: sudo chown -R root /var/www/html